version: '3'

# Containers we're going to run.
services:
   # Our Phoenix container.
   api:
      build: ./api
      image: myapp:1.0
      environment: 
         - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
      ports:
         - 4000:4000
      depends_on:
         - mongodb

   mongodb:
      image: mongo:5.0
      environment:
         - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
         - MONGO_INITDB_ROOT_PASSWORD=hunter2

   front:
      build: ./front-office/money-count
      image: front
      restart: always
      depends_on:
          - api
      ports:
          - "3001:3001"
      expose:
          - 3001
      #volumes:
      #   - ./front-end/:/code/
      #   - /code/node_modules
   
   # Services de tableau de bord de sécurité
   grafana:
      image: grafana/grafana:latest
      ports:
         - "3000:3000"
      volumes:
         - grafana-storage:/var/lib/grafana
      environment:
         - GF_SECURITY_ADMIN_USER=admin
         - GF_SECURITY_ADMIN_PASSWORD=securepassword
      depends_on:
         - prometheus
      
   prometheus:
      image: prom/prometheus:latest
      ports:
         - "9090:9090"
      volumes:
         - ./prometheus:/etc/prometheus
         - prometheus-data:/prometheus
      command:
         - '--config.file=/etc/prometheus/prometheus.yml'
   
   security-exporter:
      build: ./security-exporter
      ports:
         - "8080:8080"

# Volumes definition
volumes:
   grafana-storage:
   prometheus-data: