name: Security Monitoring

on:
  workflow_run:
    workflows: ["Security Checks"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: security-alerts
          SLACK_COLOR: danger
          SLACK_TITLE: Security Workflow Failed
          SLACK_MESSAGE: 'Security vulnerabilities detected! Please check the latest scan results.'